branch-defaults:
  default:
    environment: null
environment-defaults:
  Application-production-1:
    branch: null
    repository: null
global:
  application_name: HOUSE_PRICE
  default_ec2_keyname: null
  default_platform: 3.8
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application